# Generated by Django 3.0.5 on 2020-05-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200514_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentarticleuserrel',
            options={'verbose_name': '评论(article2user)', 'verbose_name_plural': '评论(article2user)'},
        ),
    ]
