# Generated by Django 3.0.5 on 2020-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200514_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='标题', max_length=255, verbose_name='标题'),
        ),
    ]
