# Generated by Django 3.0.5 on 2020-05-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200515_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='content_ck',
        ),
    ]
